### ISSUE TITLE
Do not force config path to be relative to binary location

### ISSUE THREAD

**Issue by Roguelazer** [Luxurioust/aurora#1]
If I invoke aurora as follows:

   /path/to/bin/aurora -c /etc/aurora.toml

I expect it to read the config from `/etc/aurora.toml`; however, it instead tries to read from `/path/to/bin/etc/aurora.toml` (that is to say, it always interprets the config path to be relative to the directory the executable is in).

**Comment by Luxurioust** [comment]
@Roguelazer Thanks for your issue. I have fix this bug and make a [release 1.7](https://github.com/Luxurioust/aurora/releases), please upgrade to the last version.
