### ISSUE TITLE
Allow bypassing openPage()

### ISSUE THREAD

**Issue by Roguelazer** [Luxurioust/aurora#2]
On launch, aurora attempts to open a browser in the `openPage` function. This really only makes sense in testing, and shouldn't be attempted by default.

This also doesn't work if you're binding to a wildcard (e.g., to `0.0.0.0` or `[::]`)

**Comment by Luxurioust** [comment]
@Roguelazer Thanks for your issue. I have added a `openpage` section in config file, if set `enabled = false` will not automatically open the browser. Note that we need to set the port for listening address, use `0.0.0.0:80` instead of `0.0.0.0`.
