### ISSUE TITLE
how to install aurora

### ISSUE THREAD

**Issue by jackerzhou** [Luxurioust/aurora#4]
Is there any document,how to install aurora

**Comment by Luxurioust** [comment]
Thanks for your issue. You can download [Precompiled binaries](https://github.com/Luxurioust/aurora/releases) for supported operating systems. Extract the zip file after download and double-click to run. If you have any questions or concerns, please let me know by replying to this issue.

**Comment by Luxurioust** [comment]
@jackerzhou Thanks for your issue. You can download [Precompiled binaries](https://github.com/Luxurioust/aurora/releases) for supported operating systems. Extract the zip file after download and double-click to run. If you have any questions or concerns, please let me know by replying to this issue.
