### ISSUE TITLE
Unknown Brew Formulae

### ISSUE THREAD

**Issue by spellett** [Luxurioust/aurora#5]
I was unable to find the brew formulae for the project. Can you please list in the readme?

**Comment by Luxurioust** [comment]
@spellett Thanks for your issue. I have sent pull requests to submit to [homebrew-core](https://github.com/Homebrew/homebrew-core/pull/6751) and [homebrew-cask](https://github.com/caskroom/homebrew-cask/pull/26600), but they unmerged commits. I will resend again a couple of months later.  Please download precompiled binaries for supported operating systems recently.

**Comment by ndelvalle** [comment]
@xuri maybe you can publish it on an aurora tap so we can download it from there :)

**Comment by ndelvalle** [comment]
`brew install aurora` is available now 🙌🏻. I think is worth adding it to the readme.

**Comment by xuri** [comment]
@ndelvalle Thanks for your info! I have added it to the readme.
