### ISSUE TITLE
Suuport setting ttr in samples

### ISSUE THREAD

**Issue by adizhol** [Luxurioust/aurora#6]
Hi,

It seems like inserting  new job sample always setts ttr to 60 secs.
Would be useful if user can be allowed to set it as part of a sample data.

Thanks

**Comment by Luxurioust** [comment]
@adizhol Thanks for your issue. I have added support setting TTR in add sample jobs and make a release. Please upgrade to [the last version](https://github.com/Luxurioust/aurora/releases).
