### ISSUE TITLE
Could I use this directly on a server?

### ISSUE THREAD

**Issue by JusticeChow** [Luxurioust/aurora#7]
I want to run it on a server, and access it from my own computer. But it seems this acquires the browser to run. Since I do not have a Xwindow on the server, is it possible to run it on server?

**Comment by Luxurioust** [comment]
Of course, you can. Just set `listen` address with your server IP and set `[openpage]` setting `enabled` to `false` in `aurora.toml`.

**Comment by JusticeChow** [comment]
3Q! I didn't notice there is a _toml_ file.
