### ISSUE TITLE
Running Aurora on boot

### ISSUE THREAD

**Issue by ecowed** [Luxurioust/aurora#8]
Hi,

Using an Ubuntu Server to run beanstalkd and aurora - do you have any example scripts/details about writing an init.d script for aurora? 

Thanks for the awesome tool!

**Comment by Luxurioust** [comment]
@ecowed Thanks for your issue. I suggest that use [Supervisor](http://supervisord.org) to manage aurora.

**Comment by ecowed** [comment]
Ah perfect - thanks! 👍
